-- Importa los 131 proyectos activos del Excel maestro de proyectos
-- (Lista_de_Proyectos.xlsx, columna Activo = 'SI', compartido 2026-08-27).
-- Los 195 inactivos no se importan por ahora (decisión del cliente) --
-- se pueden traer después para consulta histórica si hace falta.
--
-- El nombre de empresa del Excel no coincide carácter por carácter con
-- empresas.nombre (sin coma, sin acentos: "Mario Contreras Farfan" vs
-- "Mario Contreras Farfán") -- se resuelve con normalizar_texto_sql, la
-- misma función que ya usa sincronizar_catalogo_oc_ov para este mismo
-- problema contra la API del backoffice.
--
-- responsable_id/comprador_id quedan NULL: son nombres de persona
-- importados como texto (responsable_nombre/comprador_nombre), no cuentas
-- todavía -- un admin los vincula a un profile real desde el panel en
-- cuanto esa persona tenga cuenta. Placeholders genéricos del Excel
-- ("Residente", "Comprador" sin nombre real) se conservan tal cual en el
-- texto -- no se inventan cuentas para ellos.
with datos (id_backoffice, nombre, empresa_excel, comprador_nombre, responsable_nombre, tipo, seguimiento) as (
  values
(330, 'ICSA', 'Constructora Supervisión y Consultoría LOMA', 'Comprador', 'Residente', 'No establecido', 'SI'),
  (329, 'PLAZA STOP LOMAS', 'Aceros y Envasados de Puebla', 'Comprador', 'Residente', 'No establecido', 'SI'),
  (328, '4590224213 Suministro de Señaletica Carga Maxima', 'Ergodinova', 'Comprador', 'Alberto Temalatzi Arroyo', 'No establecido', 'NO'),
  (327, 'UAEM', 'Constructora Supervisión y Consultoría LOMA', 'Comprador', 'Residente', 'No establecido', 'SI'),
  (326, 'Parque Real 63', 'Mario Contreras Farfan', 'Comprador', 'Timoteo Colapala Barrientos', 'Viviendas residenciales', 'SI'),
  (325, 'Torres Antal - CCTV: suministro DVR, cámaras y reubicación de salida de video', 'QX Soluciones Globales en Tecnología y Software Empresarial', 'Comprador', 'Residente', 'No establecido', 'SI'),
  (324, '4590223490 SSVW PLATAFORMAS ESTRUC. TIGUAN HEV N-4', 'Ergodinova', 'Comprador', 'Jorge Esperón Ashworth', 'No establecido', 'SI'),
  (323, '4590222604 SSVW M. Corr. O. Civil Dic 2025-Abr 2026', 'Ergodinova', 'Comprador', 'Alma Andrea Velazquez Trejo', 'No establecido', 'SI'),
  (322, '4590221969 SSVW Reestructuración de nave 40 para Ac', 'Ergodinova', 'Comprador', 'Mauro Xilot China', 'No establecido', 'SI'),
  (321, 'SERVICIO ESPECIALIZADO EN REPARACIÓN Y SELLADO DE FISURAS PARA EMBARCACION TIPO SCAVENGER 2000DENOMINADA PUEBLA', 'Ergodinova', 'Comprador', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (320, 'TALLER CARPINTERIA', 'Constructora Supervisión y Consultoría LOMA', 'Comprador', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (319, '4590220882  Pisos Falla geológica N21', 'Ergodinova', 'Comprador', 'Guadalupe Navarro Flores', 'No establecido', 'SI'),
  (318, '4590217754 SSVW Trab Obra Civil Kiosko N75', 'Ergodinova', 'Comprador', 'Timoteo Colapala Barrientos', 'No establecido', 'SI'),
  (317, '4590218457 Saneamiento y adecuación Prensas Nave 01', 'Ergodinova', 'Comprador', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (316, '4590218696 SSVW Adec. estanterías, mallas en N29D', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (315, '4590218089 SSVW Cancel Of. Revision', 'Ergodinova', 'Comprador', 'Jorge Esperón Ashworth', 'No establecido', 'SI'),
  (314, '4590217559 Desmontaje de puerta corrediza acustica', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (313, 'Teziutlán', 'Aceros y Envasados de Puebla', 'Comprador', 'Mario Contreras Angeles', 'No establecido', 'NO'),
  (312, 'CONSTRUCCIÓN DE PAVIMENTO KINTE CON ADOQUÍN, CUAUTLANCINGO,,PUEBLA', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Terracerías', 'SI'),
  (311, '4590217230 SSVW AMPLIACIÓN PLAT. RAHMEN Y VP3 N-21', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Jorge Esperón Ashworth', 'No establecido', 'SI'),
  (310, 'Abarrotes Neto Apetatitlán', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Mauro Xilot China', 'No establecido', 'SI'),
  (309, 'Mantenimiento Domo N73', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Blanca Lilia Chavez Guridi', 'No establecido', 'SI'),
  (308, '4590216453 SSVW Cambio 5000 a 6500', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (307, 'Corporativo CSC - Mantenimiento', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (306, 'Mantenimiento Vicios Ocultos', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Timoteo Colapala Barrientos', 'No establecido', 'SI'),
  (305, 'Abarrotes Neto Huixcolotla', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Mauro Xilot China', 'No establecido', 'SI'),
  (304, '4590213180 Desmontaje estanterias proyecto Golf Log', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (303, 'SECUNDARIA OCTAVIO PAZ  PUEBLA', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Remodelaciones de escuelas', 'SI'),
  (302, 'PRIMARIA PROFESOR CARLOS SAYAGO HERNÁNDEZ PUEBLA', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Remodelaciones de escuelas', 'SI'),
  (301, 'PRIMARIA LICENCIADO ADOLFO LOPEZ MATEOS  LA LIBERTAD TECOLA PUEBLA', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Remodelaciones de escuelas', 'SI'),
  (300, 'PREESCOLAR GREGORIO TORRES QUINTERO PUEBLA', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Remodelaciones de escuelas', 'SI'),
  (299, 'PREESCOLAR MARGARITA MORAN VELIZ RESURECCION PUEBLA', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Remodelaciones de escuelas', 'SI'),
  (298, 'Abarrotes Neto Toluca', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (297, '4590213765 Impermeabilización en anexo nave 71', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Blanca Lilia Chavez Guridi', 'No establecido', 'SI'),
  (296, '4590213789 APERIODICOS CUBIERTAS 2025', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Jorge Esperón Ashworth', 'No establecido', 'SI'),
  (295, '4590214045  SSVW Adecuación fachada nave 1', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (293, '24 Biodigestores San Matías Tlalancaleca', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (292, '15 Biodigestores San Matías Tlalancaleca', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (291, 'Abarrotes Neto Huejutla', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (290, 'PROGRAMA DE REVESTIMIENTO, CALLES TRINIDAD CHAUTENCO, CUAUTLANCINGO, PUEBLA', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Pavimentación (vías terrestres)', 'SI'),
  (289, 'CASA JO DRENAJE', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Timoteo Colapala Barrientos', 'Drenaje (vías terrestres)', 'SI'),
  (288, 'Remodelación Sanitarios Oficinas GA', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Blanca Lilia Chavez Guridi', 'No establecido', 'SI'),
  (287, 'Monterreal 19', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Fernando Saenz de Miera Cuautlayol_CSC', 'Viviendas residenciales', 'SI'),
  (286, 'Monterreal 17', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Fernando Saenz de Miera Cuautlayol_CSC', 'Viviendas residenciales', 'SI'),
  (285, 'Parque Real 42', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Timoteo Colapala Barrientos', 'Viviendas residenciales', 'SI'),
  (284, '4590211135 SUMINISTRO E INSTALACIÓN DE LETREROS PAR', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (283, '4590210349 Suministro y Colocación de Postes', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Blanca Lilia Chavez Guridi', 'No establecido', 'SI'),
  (282, 'Obra Manolo Orellana', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Timoteo Colapala Barrientos', 'Viviendas residenciales', 'SI'),
  (281, 'Abarrotes Neto Monteblanco', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Construcciones no residenciales', 'SI'),
  (280, 'Plaza Morillotla', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (275, '4590209588 Fabricación y suministro de Protecciones', 'Ergodinova', 'Comprador', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (274, 'OC 44590209474, SSVW Cambio 5000 a 6500', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (273, 'FRACCIONAMIENTO ZAMORATLA', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Fernando Saenz de Miera Cuautlayol_CSC', 'Construcciones no residenciales', 'SI'),
  (272, 'TECHUMBRE DE PERFILES DE ACERO CON CUBIERTA DE PLASTICO PARA INVERNADERO AL 25% CAL. 720', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (271, 'SERVICIO DE MANTENIMIENTO CORRECTIVO A LA EMBARCACIÓN TIPO SCAVENGER 2000', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Plantas para tratamiento de agua', 'SI'),
  (270, 'Remodelación Mayorazgo', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Remodelaciones en general', 'SI'),
  (269, 'DRAGON de KOMODO FASE 3', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (268, 'DRAGON de KOMODO FASE 2', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (267, 'DRAGON de KOMODO FASE 1', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Construcciones no residenciales', 'SI'),
  (266, 'Taller Herreria', 'Mallas y Clavos Clavicon', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'NO'),
  (265, '4590207349 AJUSTE DE CABLES Y POSTES', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Blanca Lilia Chavez Guridi', 'No establecido', 'SI'),
  (264, 'SSVW Obra Civil reubicación drenaje Av B', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Jorge Esperón Ashworth', 'Drenaje (vías terrestres)', 'SI'),
  (263, '4590206616 Sum. e instalación de cable de aceros', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Blanca Lilia Chavez Guridi', 'No establecido', 'SI'),
  (262, 'Remodelación Sanitarios Caballeros N77', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Blanca Lilia Chavez Guridi', 'No establecido', 'SI'),
  (261, 'ML Hospedajes', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Iris Vianey León Flores', 'Viviendas residenciales', 'NO'),
  (260, 'Abarrotes Neto 11 Barrio de San Sebastian', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Shaday Cruz Bengoa - BBVA', 'No establecido', 'SI'),
  (259, 'Torre Antal Administración', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Iris Vianey León Flores', 'No establecido', 'SI'),
  (258, 'BAU_WCA60_MS_EV_MG2M1', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alberto Temalatzi Arroyo', 'Construcciones no residenciales', 'SI'),
  (257, 'Taller Aluminio', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'NO'),
  (256, 'MG2M1_RG_A24_STORM_WATER_DRAINAGE', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alma Andrea Velazquez Trejo', 'Agua potable (material contratista) urbanización', 'SI'),
  (255, 'Fab, Sum. Inst. de protec. a estanteria 4590204802', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (254, 'Jorge Esperon', 'Constructora Supervisión y Consultoría LOMA', 'Comprador', 'Iris Vianey León Flores', 'No establecido', 'SI'),
  (253, 'Fab, Sum. Inst. de protec. a estanteria 4590204785', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (252, 'TRES RIOS 37', 'Aceros y Envasados de Puebla', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Viviendas residenciales', 'NO'),
  (251, 'MG2M1_RU_A00_ Cuarto eléctrico Sub. MT.', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alberto Temalatzi Arroyo', 'Construcciones no residenciales', 'SI'),
  (250, 'MCF', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'NO'),
  (249, 'LUBCEN', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Fernando Saenz de Miera Cuautlayol_CSC', 'Construcciones no residenciales', 'SI'),
  (248, 'Parque Real', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'ARELI GONZALEZ ROMERO', 'Viviendas residenciales', 'SI'),
  (247, 'CEMENTERA 66', 'Aceros y Envasados de Puebla', 'Laura Socorro Orta Zepeda', 'Miguel Angel Tepal Sanchez', 'No establecido', 'NO'),
  (246, 'Aasan WC', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Construcciones no residenciales', 'NO'),
  (245, 'Secundaria del Centro Escolar Héroes de Zacapoaxtla', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Residente', 'Escuelas de estructura de concreto', 'SI'),
  (243, 'SSVW Remodelación sanitarios N77', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Blanca Lilia Chavez Guridi', 'Remodelaciones en general', 'SI'),
  (242, 'OC 4590197576 SSVW Mantenimiento', 'Ergodinova', 'Laura Socorro Orta Zepeda', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (240, 'Suministro de tubería ADS corrugado', 'Ergodinova', 'Laura Socorro Orta Zepeda', 'Miguel Angel Tepal Sanchez', 'Drenajes (material contratista) urbanización', 'SI'),
  (239, 'Fab., Sum. e Inst. de protecicones F', 'Ergodinova', 'Laura Socorro Orta Zepeda', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (238, 'Ampliación O.C. 4590185519 estant. N22', 'Ergodinova', 'Laura Socorro Orta Zepeda', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (237, 'SSVW Remodelación Of Gerencia Montaje N4', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (236, 'Portamar', 'Constructora Supervisión y Consultoría LOMA', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (235, 'Bulgaria 28', 'Aceros y Envasados de Puebla', 'Laura Socorro Orta Zepeda', 'Miguel Angel Tepal Sanchez', 'No establecido', 'SI'),
  (234, 'Oaxaca #44, Cluster Parque Oaxaca', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Miguel Angel Tepal Sanchez', 'Viviendas residenciales', 'SI'),
  (233, 'Cable para SUMAs Tayron', 'Ergodinova', 'Comprador', 'Mario Contreras Farfán', 'No establecido', 'SI'),
  (232, 'Cuidala', 'Aceros y Envasados de Puebla', 'Comprador', 'Mario Contreras Farfán', 'No establecido', 'NO'),
  (231, 'Reubicación de cabina de Pintura de Nave 26 a Nave 38 B', 'Ergodinova', 'Comprador', 'Mario Contreras Farfán', 'No establecido', 'SI'),
  (230, 'Silesia 41', 'Aceros y Envasados de Puebla', 'Comprador', 'Mario Contreras Farfán', 'No establecido', 'NO'),
  (229, 'ARMERIA 17', 'Vigueta Bovedilla y Bloques Balken', 'Comprador', 'Mario Contreras Farfán', 'No establecido', 'SI'),
  (228, 'Bachillerato José Luis Rodríguez U-2C', 'Aceros y Envasados de Puebla', 'Comprador', 'Mario Contreras Farfán', 'No establecido', 'SI'),
  (227, 'Preescolar Kabah U-1C', 'Aceros y Envasados de Puebla', 'Comprador', 'Mario Contreras Farfán', 'No establecido', 'SI'),
  (226, 'Volteo International', 'Constructora Supervisión y Consultoría LOMA', 'Comprador', 'Mario Contreras Farfán', 'No establecido', 'NO'),
  (218, 'BBVA Puebla', 'Constructora Supervisión y Consultoría LOMA', 'Comprador', 'Christian Alberto Bonifacio Xilot', 'Construcciones no residenciales', 'SI'),
  (216, 'BBVA Tlaxcala', 'Constructora Supervisión y Consultoría LOMA', 'Comprador', 'Christian Alberto Bonifacio Xilot', 'No establecido', 'SI'),
  (215, 'CASA JO', 'Constructora Supervisión y Consultoría LOMA', 'Comprador', 'Timoteo Colapala Barrientos', 'No establecido', 'SI'),
  (214, 'Estantería Covadonga', 'Ergodinova', 'Comprador', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (213, 'Instalar Postes Covadonga N6,7 Y 8', 'Ergodinova', 'Comprador', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (211, 'CUBIERTAS APERIODICOS 2024', 'Ergodinova', 'Comprador', 'Residente', 'No establecido', 'SI'),
  (210, 'CUBIERTAS DT ETAPA II 2024', 'Ergodinova', 'Lorena Contreras Farfán', 'Residente', 'No establecido', 'SI'),
  (208, 'SSVW Servicio obra civil + accesorios en Sanitarios DT', 'Ergodinova', 'Miguel Angel Huerta Godos', 'Blanca Lilia Chavez Guridi', 'Construcciones no residenciales', 'SI'),
  (204, 'Monterreal 1 - Alquitara', 'Mario Contreras Farfan', 'Comprador', 'Alfonso Baez Garcia', 'Viviendas residenciales', 'SI'),
  (202, '2da (segunda) APERIODICOS 2023 CUBIERTAS', 'Ergodinova', 'Comprador', 'Residente', 'No establecido', 'SI'),
  (201, 'Cancha de futbol Bositos', 'Mario Contreras Farfan', 'Comprador', 'Fernando Saenz de Miera Cuautlayol_CSC', 'No establecido', 'SI'),
  (199, 'BBVA Pachuca', 'Constructora Supervisión y Consultoría LOMA', 'Comprador', 'Shaday Cruz Bengoa - BBVA', 'Construcciones no residenciales', 'SI'),
  (198, 'Monterreal 05', 'Mario Contreras Farfan', 'Comprador', 'Alfonso Baez Garcia', 'No establecido', 'SI'),
  (197, 'Instalación 20 módulos estantería N22', 'Ergodinova', 'Comprador', 'Residente', 'No establecido', 'SI'),
  (191, 'Canchas de Pádel Lomas', 'Constructora Supervisión y Consultoría LOMA', 'Comprador', 'Alfonso Baez Garcia', 'No establecido', 'SI'),
  (182, 'Biodigestor Huauchinango', 'Constructora Supervisión y Consultoría LOMA', 'Lorena Contreras Farfán', 'Mario Contreras Farfán', 'No establecido', 'SI'),
  (175, 'Q5 NF_A70 Estantería pesada', 'Ergodinova', 'Comprador', 'Alberto Temalatzi Arroyo', 'No establecido', 'SI'),
  (174, 'PASEO #6', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Maria Fernanda Alejandro Cruz', 'No establecido', 'SI'),
  (173, 'CUBIERTAS DE DESARROLLO TÉCNICO (4590180940)', 'Ergodinova', 'Comprador', 'Blanca Lilia Chavez Guridi', 'No establecido', 'SI'),
  (161, 'Morillotla JV', 'Aceros y Envasados de Puebla', 'Comprador', 'ARELI GONZALEZ ROMERO', 'No establecido', 'SI'),
  (155, 'RELOCALIZACION ESTANTERÍAS COVADONGA', 'Ergodinova', 'Comprador', 'Residente', 'No establecido', 'SI'),
  (151, 'Terravita 2', 'Mario Contreras Farfan', 'Comprador', 'Residente', 'No establecido', 'SI'),
  (98, 'Corporativo Mario Contreras Farfán', 'Aceros y Envasados de Puebla', 'Comprador', 'Residente', 'No establecido', 'SI'),
  (97, 'Corporativo CLAVICON', 'Mallas y Clavos Clavicon', 'Comprador', 'Erendira Solis Tecuatl', 'No establecido', 'NO'),
  (53, 'Torre Antal Mantenimiento', 'Mario Contreras Farfan', 'Miguel Angel Huerta Godos', 'Christian Alberto Bonifacio Xilot', 'No establecido', 'SI'),
  (50, 'Corporativo LRT', 'Loma Racing Team', 'Comprador', 'Erendira Solis Tecuatl', 'No establecido', 'NO'),
  (48, 'Corporativo QX', 'QX Soluciones Globales en Tecnología y Software Empresarial', 'Comprador', 'Residente', 'No establecido', 'NO'),
  (43, 'Corporativo Ergodinova', 'Ergodinova', 'Comprador', 'Erendira Solis Tecuatl', 'No establecido', 'SI'),
  (28, 'Casa Migoya', 'Constructora Supervisión y Consultoría LOMA', 'Comprador', 'Residente', 'No establecido', 'SI'),
  (19, 'Retail', 'Aceros y Envasados de Puebla', 'Comprador', 'Residente', 'No establecido', 'NO'),
  (8, 'Corporativo CSC', 'Constructora Supervisión y Consultoría LOMA', 'Comprador', 'Erendira Solis Tecuatl', 'No establecido', 'NO'),
  (7, 'Corporativo AEP', 'Aceros y Envasados de Puebla', 'Comprador', 'Erendira Solis Tecuatl', 'No establecido', 'NO'),
  (3, 'Corporativo Balken', 'Vigueta Bovedilla y Bloques Balken', 'Comprador', 'Erendira Solis Tecuatl', 'No establecido', 'NO')
)
insert into public.proyectos (id_backoffice, nombre, empresa_id, tipo, responsable_nombre, comprador_nombre, activo)
select
  d.id_backoffice,
  d.nombre,
  e.id,
  nullif(d.tipo, 'No establecido'),
  nullif(d.responsable_nombre, ''),
  nullif(d.comprador_nombre, ''),
  true
from datos d
join public.empresas e on public.normalizar_texto_sql(e.nombre) = public.normalizar_texto_sql(d.empresa_excel)
on conflict (id_backoffice) do nothing;
