-- Catálogo inicial de KPIs por área (Mario, 25-sep-2026: "cuáles debería
-- tener cada área, ponlos para irlos desarrollando"). Las claves apuntan a
-- web/src/lib/indicadores.ts; los que ahí están `enDesarrollo` aparecen en
-- gris hasta que se implementen. Ya aplicado en producción.
insert into public.kpis_organigrama (area, indicador, orden, umbral_ambar, umbral_rojo) values
  ('finanzas', 'fin_saldo_consolidado', 1, 500000, 100000),
  ('finanzas', 'fin_pagos_vencidos', 2, 1, 3),
  ('finanzas', 'fin_pagos_semana', 3, 0, 0),
  ('finanzas', 'fin_saldos_desactualizados', 4, 1, 3),
  ('finanzas', 'fin_prestamos_abiertos', 5, 1, 5),
  ('finanzas', 'fin_flujo_30d', 6, 0, 0),
  ('contabilidad', 'cont_sin_cfdi', 3, 1, 20),
  ('contabilidad', 'cont_dias_ultima_carga', 4, 7, 15),
  ('contabilidad', 'cont_cargas_error', 5, 1, 3),
  ('contabilidad', 'cont_cfdi_sin_banco', 6, 1, 20),
  ('contabilidad', 'cont_conciliacion_pct', 7, 90, 70),
  ('rh', 'rh_asistencia_hoy', 0, 85, 70),
  ('rh', 'rh_vacantes', 4, 1, 3),
  ('rh', 'rh_rotacion_mes', 5, 3, 8),
  ('rh', 'rh_firmas_pendientes', 6, 1, 5),
  ('rh', 'rh_retardos_semana', 7, 3, 10),
  ('rh', 'rh_horas_extra_semana', 8, 20, 60),
  ('almacen', 'alm_partidas_faltantes', 2, 1, 10),
  ('almacen', 'alm_partidas_excedente', 3, 1, 3),
  ('almacen', 'alm_entradas_sin_oc', 4, 1, 5),
  ('almacen', 'alm_productos_sin_costo', 5, 1, 20),
  ('almacen', 'alm_movimientos_hoy', 6, 0, 0),
  ('almacen', 'alm_valor_inventario', 7, 0, 0),
  ('logistica', 'log_ov_parciales', 3, 1, 5),
  ('logistica', 'log_requisiciones', 4, 1, 10),
  ('logistica', 'log_dias_entrega', 5, 2, 5),
  ('logistica', 'log_remisiones_semana', 6, 0, 0),
  ('logistica', 'log_entregas_a_tiempo', 7, 90, 75),
  ('mantenimiento', 'mant_folios_viejos', 2, 1, 5),
  ('mantenimiento', 'mant_folios_en_ejecucion', 3, 0, 0),
  ('mantenimiento', 'mant_folios_atendidos_semana', 4, 0, 0),
  ('mantenimiento', 'mant_asistencia_bbva', 5, 85, 70),
  ('mantenimiento', 'mant_equilibrio_mes', 6, 90, 70),
  ('operacion', 'op_ordenes_atrasadas', 3, 1, 3),
  ('operacion', 'op_operaciones_retrasadas', 4, 1, 5),
  ('operacion', 'op_pu_borrador_viejos', 5, 1, 5),
  ('operacion', 'op_tareas_vencidas', 6, 1, 10),
  ('operacion', 'op_proyectos_activos', 7, 0, 0),
  ('operacion', 'op_cumplimiento_produccion', 8, 90, 75),
  ('operacion', 'op_eficiencia_maquinas', 9, 85, 70),
  ('sistemas', 'sis_usuarios_activos_7d', 2, 0, 0),
  ('sistemas', 'sis_sync_horas', 3, 2, 24),
  ('sistemas', 'sis_fotos_error_7d', 4, 1, 3),
  ('sistemas', 'sis_accesos_sin_uso', 5, 1, 5),
  ('sistemas', 'sis_errores_app', 6, 1, 10)
on conflict (area, indicador) do nothing;
